//
// File generated by rootcint at Mon Sep 21 02:16:49 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME StPhiDownMakerDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "StPhiDownMakerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void StPhiDownMaker_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_StPhiDownMaker(void *p);
   static void deleteArray_StPhiDownMaker(void *p);
   static void destruct_StPhiDownMaker(void *p);
   static void streamer_StPhiDownMaker(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::StPhiDownMaker*)
   {
      ::StPhiDownMaker *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::StPhiDownMaker >(0);
      static ::ROOT::TGenericClassInfo 
         instance("StPhiDownMaker", ::StPhiDownMaker::Class_Version(), "./StPhiDownMaker.hh", 9,
                  typeid(::StPhiDownMaker), ::ROOT::DefineBehavior(ptr, ptr),
                  &::StPhiDownMaker::Dictionary, isa_proxy, 0,
                  sizeof(::StPhiDownMaker) );
      instance.SetDelete(&delete_StPhiDownMaker);
      instance.SetDeleteArray(&deleteArray_StPhiDownMaker);
      instance.SetDestructor(&destruct_StPhiDownMaker);
      instance.SetStreamerFunc(&streamer_StPhiDownMaker);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::StPhiDownMaker*)
   {
      return GenerateInitInstanceLocal((::StPhiDownMaker*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::StPhiDownMaker*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr StPhiDownMaker::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *StPhiDownMaker::Class_Name()
{
   return "StPhiDownMaker";
}

//______________________________________________________________________________
const char *StPhiDownMaker::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::StPhiDownMaker*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int StPhiDownMaker::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::StPhiDownMaker*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void StPhiDownMaker::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::StPhiDownMaker*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *StPhiDownMaker::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::StPhiDownMaker*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void StPhiDownMaker::Streamer(TBuffer &R__b)
{
   // Stream an object of class StPhiDownMaker.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> mDatFile;
      R__b >> mLevy;
      R__b >> mLevyPt;
      R__b >> mLevyPt2;
      R__b >> mTotal;
      R__b >> mBW;
      R__b >> mPolyBg;
      int R__i;
      for (R__i = 0; R__i < 9; R__i++)
         R__b >> mHFpEffFine[R__i];
      for (R__i = 0; R__i < 9; R__i++)
         R__b >> mHExpEffFine[R__i];
      for (int R__i0=0; R__i0<9; ++R__i0 )
         { TString R__str; R__str.Streamer(R__b); mCentString[R__i0] = R__str.Data();}
      for (int R__i0=0; R__i0<9; ++R__i0 )
         { TString R__str; R__str.Streamer(R__b); mCentStringBES[R__i0] = R__str.Data();}
      { TString R__str; R__str.Streamer(R__b); mParticleType = R__str.Data(); }
      R__b >> pdgmass_phi;
      R__b >> mKCentBin;
      R__b >> mKCentBinBES;
      R__b >> mKCentBin2;
      R__b >> mKPtBin;
      R__b.ReadStaticArray((double*)mNEventsUnweighted);
      R__b.ReadStaticArray((double*)mNEventsWeighted);
      R__b.ReadStaticArray((double*)mNEventsWeightedBES);
      R__b >> mBr;
      R__b >> mSigRangeLeft;
      R__b >> mSigRangeRight;
      R__b >> mMixNormLeftLowB;
      R__b >> mMixNormLeftHighB;
      R__b >> mMixNormRightLowB;
      R__b >> mMixNormRightHighB;
      R__b.ReadStaticArray((double*)mPtBd);
      R__b.ReadStaticArray((double*)mFpEff);
      R__b.ReadStaticArray((double*)mFpEffError);
      R__b.ReadStaticArray((double*)mExpEff);
      R__b.ReadStaticArray((double*)mExpEffError);
      R__b.ReadStaticArray((double*)mEff);
      R__b.ReadStaticArray((double*)mEffError);
      R__b.ReadStaticArray((double*)mMixScale_ratio);
      R__b.ReadStaticArray((double*)mRawSigCounts);
      R__b.ReadStaticArray((double*)mRawSigCountsError);
      R__b.ReadStaticArray((double*)mXRawSpectra);
      R__b.ReadStaticArray((double*)mXRawSpectraError);
      R__b.ReadStaticArray((double*)mYRawSpectra);
      R__b.ReadStaticArray((double*)mYRawSpectraScale);
      R__b.ReadStaticArray((double*)mYRawSpectraError);
      R__b.ReadStaticArray((double*)mYRawSpectraErrorScale);
      R__b.ReadStaticArray((double*)mDptSpectra);
      R__b.ReadStaticArray((double*)mXCorrSpectra);
      R__b.ReadStaticArray((double*)mYCorrSpectra);
      R__b.ReadStaticArray((double*)mYCorrSpectraScale);
      R__b.ReadStaticArray((double*)mYCorrSpectraError);
      R__b.ReadStaticArray((double*)mYCorrSpectraErrorScale);
      R__b.ReadStaticArray((double*)mLevyPar);
      R__b.ReadStaticArray((double*)mLevyParError);
      R__b.ReadStaticArray((double*)mInvMassPar);
      R__b.ReadStaticArray((double*)mInvMassParError);
      R__b.ReadStaticArray((double*)mDndy);
      R__b.ReadStaticArray((double*)mDndyError);
      R__b.ReadStaticArray((double*)mDndyFit);
      R__b.ReadStaticArray((double*)mRawSigCountsBES);
      R__b.ReadStaticArray((double*)mRawSigCountsBESError);
      R__b.ReadStaticArray((double*)mXRawSpectraBES);
      R__b.ReadStaticArray((double*)mXRawSpectraBESError);
      R__b.ReadStaticArray((double*)mYRawSpectraBES);
      R__b.ReadStaticArray((double*)mYRawSpectraBESScale);
      R__b.ReadStaticArray((double*)mYRawSpectraBESError);
      R__b.ReadStaticArray((double*)mYRawSpectraBESErrorScale);
      R__b.ReadStaticArray((double*)mXCorrSpectraBES);
      R__b.ReadStaticArray((double*)mYCorrSpectraBES);
      R__b.ReadStaticArray((double*)mYCorrSpectraBESScale);
      R__b.ReadStaticArray((double*)mYCorrSpectraBESError);
      R__b.ReadStaticArray((double*)mYCorrSpectraBESErrorScale);
      R__b.ReadStaticArray((double*)mLevyParBES);
      R__b.ReadStaticArray((double*)mLevyParBESError);
      R__b.ReadStaticArray((double*)mDndyBES);
      R__b.ReadStaticArray((double*)mDndyBESError);
      R__b.ReadStaticArray((double*)mDndyFitBES);
      R__b.CheckByteCount(R__s, R__c, StPhiDownMaker::IsA());
   } else {
      R__c = R__b.WriteVersion(StPhiDownMaker::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << mDatFile;
      R__b << mLevy;
      R__b << mLevyPt;
      R__b << mLevyPt2;
      R__b << mTotal;
      R__b << mBW;
      R__b << mPolyBg;
      int R__i;
      for (R__i = 0; R__i < 9; R__i++)
         R__b << (TObject*)mHFpEffFine[R__i];
      for (R__i = 0; R__i < 9; R__i++)
         R__b << (TObject*)mHExpEffFine[R__i];
      for (int R__i0=0; R__i0<9; ++R__i0 )
         { TString R__str(mCentString[R__i0].c_str()); R__str.Streamer(R__b);}
      for (int R__i0=0; R__i0<9; ++R__i0 )
         { TString R__str(mCentStringBES[R__i0].c_str()); R__str.Streamer(R__b);}
      { TString R__str = mParticleType.c_str(); R__str.Streamer(R__b);}
      R__b << pdgmass_phi;
      R__b << mKCentBin;
      R__b << mKCentBinBES;
      R__b << mKCentBin2;
      R__b << mKPtBin;
      R__b.WriteArray(mNEventsUnweighted, 9);
      R__b.WriteArray(mNEventsWeighted, 9);
      R__b.WriteArray(mNEventsWeightedBES, 6);
      R__b << mBr;
      R__b << mSigRangeLeft;
      R__b << mSigRangeRight;
      R__b << mMixNormLeftLowB;
      R__b << mMixNormLeftHighB;
      R__b << mMixNormRightLowB;
      R__b << mMixNormRightHighB;
      R__b.WriteArray(mPtBd, 12);
      R__b.WriteArray((double*)mFpEff, 99);
      R__b.WriteArray((double*)mFpEffError, 99);
      R__b.WriteArray((double*)mExpEff, 99);
      R__b.WriteArray((double*)mExpEffError, 99);
      R__b.WriteArray((double*)mEff, 99);
      R__b.WriteArray((double*)mEffError, 99);
      R__b.WriteArray((double*)mMixScale_ratio, 99);
      R__b.WriteArray((double*)mRawSigCounts, 99);
      R__b.WriteArray((double*)mRawSigCountsError, 99);
      R__b.WriteArray(mXRawSpectra, 11);
      R__b.WriteArray(mXRawSpectraError, 11);
      R__b.WriteArray((double*)mYRawSpectra, 99);
      R__b.WriteArray((double*)mYRawSpectraScale, 99);
      R__b.WriteArray((double*)mYRawSpectraError, 99);
      R__b.WriteArray((double*)mYRawSpectraErrorScale, 99);
      R__b.WriteArray(mDptSpectra, 11);
      R__b.WriteArray((double*)mXCorrSpectra, 99);
      R__b.WriteArray((double*)mYCorrSpectra, 99);
      R__b.WriteArray((double*)mYCorrSpectraScale, 99);
      R__b.WriteArray((double*)mYCorrSpectraError, 99);
      R__b.WriteArray((double*)mYCorrSpectraErrorScale, 99);
      R__b.WriteArray((double*)mLevyPar, 27);
      R__b.WriteArray((double*)mLevyParError, 27);
      R__b.WriteArray((double*)mInvMassPar, 297);
      R__b.WriteArray((double*)mInvMassParError, 297);
      R__b.WriteArray(mDndy, 9);
      R__b.WriteArray(mDndyError, 9);
      R__b.WriteArray(mDndyFit, 9);
      R__b.WriteArray((double*)mRawSigCountsBES, 66);
      R__b.WriteArray((double*)mRawSigCountsBESError, 66);
      R__b.WriteArray(mXRawSpectraBES, 11);
      R__b.WriteArray(mXRawSpectraBESError, 11);
      R__b.WriteArray((double*)mYRawSpectraBES, 66);
      R__b.WriteArray((double*)mYRawSpectraBESScale, 66);
      R__b.WriteArray((double*)mYRawSpectraBESError, 66);
      R__b.WriteArray((double*)mYRawSpectraBESErrorScale, 66);
      R__b.WriteArray((double*)mXCorrSpectraBES, 66);
      R__b.WriteArray((double*)mYCorrSpectraBES, 66);
      R__b.WriteArray((double*)mYCorrSpectraBESScale, 66);
      R__b.WriteArray((double*)mYCorrSpectraBESError, 66);
      R__b.WriteArray((double*)mYCorrSpectraBESErrorScale, 66);
      R__b.WriteArray((double*)mLevyParBES, 18);
      R__b.WriteArray((double*)mLevyParBESError, 18);
      R__b.WriteArray(mDndyBES, 6);
      R__b.WriteArray(mDndyBESError, 6);
      R__b.WriteArray(mDndyFitBES, 6);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void StPhiDownMaker::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class StPhiDownMaker.
      TClass *R__cl = ::StPhiDownMaker::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mDatFile", &mDatFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mLevy", &mLevy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mLevyPt", &mLevyPt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mLevyPt2", &mLevyPt2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mTotal", &mTotal);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mBW", &mBW);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mPolyBg", &mPolyBg);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mHFpEffFine[9]", &mHFpEffFine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mHExpEffFine[9]", &mHExpEffFine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mCentString[9]", mCentString);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mCentStringBES[9]", mCentStringBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mParticleType", (void*)&mParticleType);
      R__insp.InspectMember("string", (void*)&mParticleType, "mParticleType.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdgmass_phi", &pdgmass_phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKCentBin", &mKCentBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKCentBinBES", &mKCentBinBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKCentBin2", &mKCentBin2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKPtBin", &mKPtBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mNEventsUnweighted[9]", mNEventsUnweighted);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mNEventsWeighted[9]", mNEventsWeighted);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mNEventsWeightedBES[6]", mNEventsWeightedBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mBr", &mBr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mSigRangeLeft", &mSigRangeLeft);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mSigRangeRight", &mSigRangeRight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mMixNormLeftLowB", &mMixNormLeftLowB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mMixNormLeftHighB", &mMixNormLeftHighB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mMixNormRightLowB", &mMixNormRightLowB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mMixNormRightHighB", &mMixNormRightHighB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mPtBd[12]", mPtBd);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mFpEff[9][11]", mFpEff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mFpEffError[9][11]", mFpEffError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mExpEff[9][11]", mExpEff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mExpEffError[9][11]", mExpEffError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mEff[9][11]", mEff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mEffError[9][11]", mEffError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mMixScale_ratio[9][11]", mMixScale_ratio);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRawSigCounts[9][11]", mRawSigCounts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRawSigCountsError[9][11]", mRawSigCountsError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectra[11]", mXRawSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectraError[11]", mXRawSpectraError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectra[9][11]", mYRawSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraScale[9][11]", mYRawSpectraScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraError[9][11]", mYRawSpectraError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraErrorScale[9][11]", mYRawSpectraErrorScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDptSpectra[11]", mDptSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXCorrSpectra[9][11]", mXCorrSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectra[9][11]", mYCorrSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraScale[9][11]", mYCorrSpectraScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraError[9][11]", mYCorrSpectraError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraErrorScale[9][11]", mYCorrSpectraErrorScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mLevyPar[9][3]", mLevyPar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mLevyParError[9][3]", mLevyParError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mInvMassPar[9][11][3]", mInvMassPar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mInvMassParError[9][11][3]", mInvMassParError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndy[9]", mDndy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndyError[9]", mDndyError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndyFit[9]", mDndyFit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRawSigCountsBES[6][11]", mRawSigCountsBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRawSigCountsBESError[6][11]", mRawSigCountsBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectraBES[11]", mXRawSpectraBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectraBESError[11]", mXRawSpectraBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraBES[6][11]", mYRawSpectraBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraBESScale[6][11]", mYRawSpectraBESScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraBESError[6][11]", mYRawSpectraBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraBESErrorScale[6][11]", mYRawSpectraBESErrorScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXCorrSpectraBES[6][11]", mXCorrSpectraBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraBES[6][11]", mYCorrSpectraBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraBESScale[6][11]", mYCorrSpectraBESScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraBESError[6][11]", mYCorrSpectraBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYCorrSpectraBESErrorScale[6][11]", mYCorrSpectraBESErrorScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mLevyParBES[6][3]", mLevyParBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mLevyParBESError[6][3]", mLevyParBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndyBES[6]", mDndyBES);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndyBESError[6]", mDndyBESError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDndyFitBES[6]", mDndyFitBES);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_StPhiDownMaker(void *p) {
      delete ((::StPhiDownMaker*)p);
   }
   static void deleteArray_StPhiDownMaker(void *p) {
      delete [] ((::StPhiDownMaker*)p);
   }
   static void destruct_StPhiDownMaker(void *p) {
      typedef ::StPhiDownMaker current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_StPhiDownMaker(TBuffer &buf, void *obj) {
      ((::StPhiDownMaker*)obj)->::StPhiDownMaker::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::StPhiDownMaker

/********************************************************
* StPhiDownMakerDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableStPhiDownMakerDict();

extern "C" void G__set_cpp_environmentStPhiDownMakerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("StPhiDownMaker.hh");
  G__cpp_reset_tagtableStPhiDownMakerDict();
}
#include <new>
extern "C" int G__cpp_dllrevStPhiDownMakerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* StPhiDownMaker */
static int G__StPhiDownMakerDict_275_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   StPhiDownMaker* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new StPhiDownMaker(*((string*) G__int(libp->para[0])));
   } else {
     p = new((void*) gvp) StPhiDownMaker(*((string*) G__int(libp->para[0])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StPhiDownMaker*) G__getstructoffset())->Init(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StPhiDownMaker*) G__getstructoffset())->Analyze();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StPhiDownMaker*) G__getstructoffset())->AnalyzeBES();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) StPhiDownMaker::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StPhiDownMaker::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) StPhiDownMaker::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      StPhiDownMaker::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StPhiDownMaker*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StPhiDownMaker::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StPhiDownMaker::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StPhiDownMaker::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StPhiDownMakerDict_275_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StPhiDownMaker::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__StPhiDownMakerDict_275_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   StPhiDownMaker* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new StPhiDownMaker(*(StPhiDownMaker*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef StPhiDownMaker G__TStPhiDownMaker;
static int G__StPhiDownMakerDict_275_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (StPhiDownMaker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((StPhiDownMaker*) (soff+(sizeof(StPhiDownMaker)*i)))->~G__TStPhiDownMaker();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (StPhiDownMaker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((StPhiDownMaker*) (soff))->~G__TStPhiDownMaker();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__StPhiDownMakerDict_275_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   StPhiDownMaker* dest = (StPhiDownMaker*) G__getstructoffset();
   *dest = *(StPhiDownMaker*) libp->para[0].ref;
   const StPhiDownMaker& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* StPhiDownMaker */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncStPhiDownMakerDict {
 public:
  G__Sizep2memfuncStPhiDownMakerDict(): p(&G__Sizep2memfuncStPhiDownMakerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncStPhiDownMakerDict::*p)();
};

size_t G__get_sizep2memfuncStPhiDownMakerDict()
{
  G__Sizep2memfuncStPhiDownMakerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceStPhiDownMakerDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker))) {
     StPhiDownMaker *G__Lderived;
     G__Lderived=(StPhiDownMaker*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker),G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableStPhiDownMakerDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* StPhiDownMaker */
static void G__setup_memvarStPhiDownMaker(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker));
   { StPhiDownMaker *p; p=(StPhiDownMaker*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TFile),-1,-1,4,"mDatFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mLevy=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mLevyPt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mLevyPt2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mTotal=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mBW=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TF1),-1,-1,4,"mPolyBg=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TH1F),-1,-1,4,"mHFpEffFine[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TH1F),-1,-1,4,"mHExpEffFine[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_string),-1,-1,4,"mCentString[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_string),-1,-1,4,"mCentStringBES[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_string),-1,-1,4,"mParticleType=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"pdgmass_phi=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKCentBin=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKCentBinBES=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKCentBin2=",0,"This no of centrality bin is used for Physics Plots");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKPtBin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mNEventsUnweighted[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mNEventsWeighted[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mNEventsWeightedBES[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mBr=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mSigRangeLeft=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mSigRangeRight=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mMixNormLeftLowB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mMixNormLeftHighB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mMixNormRightLowB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mMixNormRightHighB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mPtBd[12]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mFpEff[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mFpEffError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mExpEff[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mExpEffError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mEff[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mEffError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mMixScale_ratio[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRawSigCounts[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRawSigCountsError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectra[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectraError[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectra[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraScale[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraErrorScale[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDptSpectra[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXCorrSpectra[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectra[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraScale[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraError[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraErrorScale[9][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mLevyPar[9][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mLevyParError[9][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mInvMassPar[9][11][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mInvMassParError[9][11][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndy[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndyError[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndyFit[9]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRawSigCountsBES[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRawSigCountsBESError[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectraBES[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectraBESError[11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraBES[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraBESScale[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraBESError[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraBESErrorScale[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXCorrSpectraBES[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraBES[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraBESScale[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraBESError[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYCorrSpectraBESErrorScale[6][11]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mLevyParBES[6][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mLevyParBESError[6][3]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndyBES[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndyBESError[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDndyFitBES[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarStPhiDownMakerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncStPhiDownMaker(void) {
   /* StPhiDownMaker */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker));
   G__memfunc_setup("effInit",709,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("levyInit",852,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bwFuncInit",1017,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("nEventsInit",1143,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("mixBgAnalysisInit",1743,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compMixNormFactor",1752,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 4, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotMixInvMassWithData",2244,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 5, 1, 4, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot "
"d - 'Double_t' 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotInvMassAfterBgSubtraction",2985,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 5, 1, 4, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot "
"d - 'Double_t' 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSigCounts",1656,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 3, 1, 4, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"d - 'Double_t' 0 - bin_width", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSigCountsBES",1874,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSpectra",1451,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSpectraBES",1669,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotRawSpectra",1467,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotRawSpectraBES",1685,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("analyzeEff",1029,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "input: eff, levy; Load efficiency raw data file and apply the cuts; output efficiency data; iteratively compute the data points", (void*) NULL, 0);
   G__memfunc_setup("getCentString",1345,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__StPhiDownMakerDictLN_string), -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotEff",720,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getSpectraWeight",1658,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 2, 1, 4, 0, 
"i - 'Int_t' 0 - - d - 'Double_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compCorrSpectra",1559,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "input: eff, xpos, levy", (void*) NULL, 0);
   G__memfunc_setup("compDndy",830,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", "Integrate the unmeasured range and add up the measured range.", (void*) NULL, 0);
   G__memfunc_setup("getDndy",719,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDndyError",1241,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 4, 0, "i - 'Int_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotCorrSpectra",1575,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("StPhiDownMaker",1392,G__StPhiDownMakerDict_275_0_24, 105, G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - par_type", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__StPhiDownMakerDict_275_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - datfile", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Analyze",724,G__StPhiDownMakerDict_275_0_26, 121, -1, -1, 0, 0, 1, 1, 0, "", "call analyzeEff(); compCorrSpectra(); analyzeEff()", (void*) NULL, 0);
   G__memfunc_setup("AnalyzeBES",942,G__StPhiDownMakerDict_275_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__StPhiDownMakerDict_275_0_28, 85, G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&StPhiDownMaker::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__StPhiDownMakerDict_275_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StPhiDownMaker::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__StPhiDownMakerDict_275_0_30, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&StPhiDownMaker::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__StPhiDownMakerDict_275_0_31, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&StPhiDownMaker::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__StPhiDownMakerDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__StPhiDownMakerDict_275_0_35, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__StPhiDownMakerDict_275_0_36, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StPhiDownMaker::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__StPhiDownMakerDict_275_0_37, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StPhiDownMaker::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__StPhiDownMakerDict_275_0_38, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StPhiDownMaker::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__StPhiDownMakerDict_275_0_39, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StPhiDownMaker::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("StPhiDownMaker", 1392, G__StPhiDownMakerDict_275_0_40, (int) ('i'), G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker), -1, 0, 1, 1, 1, 0, "u 'StPhiDownMaker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~StPhiDownMaker", 1518, G__StPhiDownMakerDict_275_0_41, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__StPhiDownMakerDict_275_0_42, (int) ('u'), G__get_linked_tagnum(&G__StPhiDownMakerDictLN_StPhiDownMaker), -1, 1, 1, 1, 1, 0, "u 'StPhiDownMaker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncStPhiDownMakerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalStPhiDownMakerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcStPhiDownMakerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__StPhiDownMakerDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TF1 = { "TF1" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__StPhiDownMakerDictLN_StPhiDownMaker = { "StPhiDownMaker" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableStPhiDownMakerDict() {
  G__StPhiDownMakerDictLN_TClass.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TBuffer.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TMemberInspector.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TObject.tagnum = -1 ;
  G__StPhiDownMakerDictLN_string.tagnum = -1 ;
  G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TF1.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TH1F.tagnum = -1 ;
  G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__StPhiDownMakerDictLN_TFile.tagnum = -1 ;
  G__StPhiDownMakerDictLN_StPhiDownMaker.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableStPhiDownMakerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_string);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TF1);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_TFile);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__StPhiDownMakerDictLN_StPhiDownMaker),sizeof(StPhiDownMaker),-1,62464,(char*)NULL,G__setup_memvarStPhiDownMaker,G__setup_memfuncStPhiDownMaker);
}
extern "C" void G__cpp_setupStPhiDownMakerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupStPhiDownMakerDict()");
  G__set_cpp_environmentStPhiDownMakerDict();
  G__cpp_setup_tagtableStPhiDownMakerDict();

  G__cpp_setup_inheritanceStPhiDownMakerDict();

  G__cpp_setup_typetableStPhiDownMakerDict();

  G__cpp_setup_memvarStPhiDownMakerDict();

  G__cpp_setup_memfuncStPhiDownMakerDict();
  G__cpp_setup_globalStPhiDownMakerDict();
  G__cpp_setup_funcStPhiDownMakerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncStPhiDownMakerDict();
  return;
}
class G__cpp_setup_initStPhiDownMakerDict {
  public:
    G__cpp_setup_initStPhiDownMakerDict() { G__add_setup_func("StPhiDownMakerDict",(G__incsetup)(&G__cpp_setupStPhiDownMakerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initStPhiDownMakerDict() { G__remove_setup_func("StPhiDownMakerDict"); }
};
G__cpp_setup_initStPhiDownMakerDict G__cpp_setup_initializerStPhiDownMakerDict;

