/********************************************************************
* StPhiDownMakerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error StPhiDownMakerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStPhiDownMakerDict();
extern void G__cpp_setup_inheritanceStPhiDownMakerDict();
extern void G__cpp_setup_typetableStPhiDownMakerDict();
extern void G__cpp_setup_memvarStPhiDownMakerDict();
extern void G__cpp_setup_globalStPhiDownMakerDict();
extern void G__cpp_setup_memfuncStPhiDownMakerDict();
extern void G__cpp_setup_funcStPhiDownMakerDict();
extern void G__set_cpp_environmentStPhiDownMakerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StPhiDownMaker.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StPhiDownMakerDictLN_TClass;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TBuffer;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TMemberInspector;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TObject;
extern G__linked_taginfo G__StPhiDownMakerDictLN_string;
extern G__linked_taginfo G__StPhiDownMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TF1;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TH1F;
extern G__linked_taginfo G__StPhiDownMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__StPhiDownMakerDictLN_TFile;
extern G__linked_taginfo G__StPhiDownMakerDictLN_StPhiDownMaker;

/* STUB derived class for protected member access */
