//
// File generated by rootcint at Wed Aug 26 22:06:58 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME StrAnalyMakerDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "StrAnalyMakerDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void StrAnalyMaker_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_StrAnalyMaker(void *p = 0);
   static void *newArray_StrAnalyMaker(Long_t size, void *p);
   static void delete_StrAnalyMaker(void *p);
   static void deleteArray_StrAnalyMaker(void *p);
   static void destruct_StrAnalyMaker(void *p);
   static void streamer_StrAnalyMaker(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::StrAnalyMaker*)
   {
      ::StrAnalyMaker *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::StrAnalyMaker >(0);
      static ::ROOT::TGenericClassInfo 
         instance("StrAnalyMaker", ::StrAnalyMaker::Class_Version(), "./StrAnalyMaker.hh", 7,
                  typeid(::StrAnalyMaker), ::ROOT::DefineBehavior(ptr, ptr),
                  &::StrAnalyMaker::Dictionary, isa_proxy, 0,
                  sizeof(::StrAnalyMaker) );
      instance.SetNew(&new_StrAnalyMaker);
      instance.SetNewArray(&newArray_StrAnalyMaker);
      instance.SetDelete(&delete_StrAnalyMaker);
      instance.SetDeleteArray(&deleteArray_StrAnalyMaker);
      instance.SetDestructor(&destruct_StrAnalyMaker);
      instance.SetStreamerFunc(&streamer_StrAnalyMaker);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::StrAnalyMaker*)
   {
      return GenerateInitInstanceLocal((::StrAnalyMaker*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::StrAnalyMaker*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr StrAnalyMaker::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *StrAnalyMaker::Class_Name()
{
   return "StrAnalyMaker";
}

//______________________________________________________________________________
const char *StrAnalyMaker::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::StrAnalyMaker*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int StrAnalyMaker::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::StrAnalyMaker*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void StrAnalyMaker::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::StrAnalyMaker*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *StrAnalyMaker::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::StrAnalyMaker*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void StrAnalyMaker::Streamer(TBuffer &R__b)
{
   // Stream an object of class StrAnalyMaker.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> mOverviewFile;
      R__b >> mDatFile;
      R__b >> mRotBgFile;
      R__b >> pdgmass_xi;
      R__b >> mKCentBin;
      R__b >> mKPtBin;
      R__b.ReadStaticArray((double*)mNEventsUnweighted);
      R__b.ReadStaticArray((double*)mNEventsWeighted);
      R__b >> mBr;
      R__b >> mSigRangeLeft;
      R__b >> mSigRangeRight;
      R__b >> mRotNormLeftLowB;
      R__b >> mRotNormLeftHighB;
      R__b >> mRotNormRightLowB;
      R__b >> mRotNormRightHighB;
      R__b.ReadStaticArray((double*)mRotScale_ratio);
      R__b.ReadStaticArray((double*)mRawSigCounts);
      R__b.ReadStaticArray((double*)mXRawSpectra);
      R__b.ReadStaticArray((double*)mXRawSpectraError);
      R__b.ReadStaticArray((double*)mYRawSpectra);
      R__b.ReadStaticArray((double*)mYRawSpectraError);
      R__b.ReadStaticArray((double*)mDptSpectra);
      R__b.CheckByteCount(R__s, R__c, StrAnalyMaker::IsA());
   } else {
      R__c = R__b.WriteVersion(StrAnalyMaker::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << mOverviewFile;
      R__b << mDatFile;
      R__b << mRotBgFile;
      R__b << pdgmass_xi;
      R__b << mKCentBin;
      R__b << mKPtBin;
      R__b.WriteArray(mNEventsUnweighted, 2);
      R__b.WriteArray(mNEventsWeighted, 2);
      R__b << mBr;
      R__b << mSigRangeLeft;
      R__b << mSigRangeRight;
      R__b << mRotNormLeftLowB;
      R__b << mRotNormLeftHighB;
      R__b << mRotNormRightLowB;
      R__b << mRotNormRightHighB;
      R__b.WriteArray((double*)mRotScale_ratio, 12);
      R__b.WriteArray((double*)mRawSigCounts, 12);
      R__b.WriteArray(mXRawSpectra, 6);
      R__b.WriteArray(mXRawSpectraError, 6);
      R__b.WriteArray((double*)mYRawSpectra, 12);
      R__b.WriteArray((double*)mYRawSpectraError, 12);
      R__b.WriteArray(mDptSpectra, 6);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void StrAnalyMaker::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class StrAnalyMaker.
      TClass *R__cl = ::StrAnalyMaker::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mOverviewFile", &mOverviewFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mDatFile", &mDatFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mRotBgFile", &mRotBgFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pdgmass_xi", &pdgmass_xi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKCentBin", &mKCentBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mKPtBin", &mKPtBin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mNEventsUnweighted[2]", mNEventsUnweighted);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mNEventsWeighted[2]", mNEventsWeighted);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mBr", &mBr);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mSigRangeLeft", &mSigRangeLeft);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mSigRangeRight", &mSigRangeRight);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRotNormLeftLowB", &mRotNormLeftLowB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRotNormLeftHighB", &mRotNormLeftHighB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRotNormRightLowB", &mRotNormRightLowB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRotNormRightHighB", &mRotNormRightHighB);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRotScale_ratio[2][6]", mRotScale_ratio);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mRawSigCounts[2][6]", mRawSigCounts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectra[6]", mXRawSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mXRawSpectraError[6]", mXRawSpectraError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectra[2][6]", mYRawSpectra);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mYRawSpectraError[2][6]", mYRawSpectraError);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mDptSpectra[6]", mDptSpectra);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_StrAnalyMaker(void *p) {
      return  p ? new(p) ::StrAnalyMaker : new ::StrAnalyMaker;
   }
   static void *newArray_StrAnalyMaker(Long_t nElements, void *p) {
      return p ? new(p) ::StrAnalyMaker[nElements] : new ::StrAnalyMaker[nElements];
   }
   // Wrapper around operator delete
   static void delete_StrAnalyMaker(void *p) {
      delete ((::StrAnalyMaker*)p);
   }
   static void deleteArray_StrAnalyMaker(void *p) {
      delete [] ((::StrAnalyMaker*)p);
   }
   static void destruct_StrAnalyMaker(void *p) {
      typedef ::StrAnalyMaker current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_StrAnalyMaker(TBuffer &buf, void *obj) {
      ((::StrAnalyMaker*)obj)->::StrAnalyMaker::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::StrAnalyMaker

/********************************************************
* StrAnalyMakerDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableStrAnalyMakerDict();

extern "C" void G__set_cpp_environmentStrAnalyMakerDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("StrAnalyMaker.hh");
  G__cpp_reset_tagtableStrAnalyMakerDict();
}
#include <new>
extern "C" int G__cpp_dllrevStrAnalyMakerDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* StrAnalyMaker */
static int G__StrAnalyMakerDict_257_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   StrAnalyMaker* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new StrAnalyMaker[n];
     } else {
       p = new((void*) gvp) StrAnalyMaker[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new StrAnalyMaker;
     } else {
       p = new((void*) gvp) StrAnalyMaker;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->Init(*((string*) G__int(libp->para[0])), *((string*) G__int(libp->para[1]))
, *((string*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->plotRotInvMassWithData((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2]), (TH1F*) G__int(libp->para[3])
, (Double_t) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->compRawSigCounts((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])
, (TH1F*) G__int(libp->para[2]), (TH1F*) G__int(libp->para[3])
, (Double_t) G__double(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->compRawSpectra();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->plotRawSpectra();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->Analyze();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) StrAnalyMaker::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StrAnalyMaker::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) StrAnalyMaker::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      StrAnalyMaker::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((StrAnalyMaker*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StrAnalyMaker::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StrAnalyMaker::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StrAnalyMaker::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__StrAnalyMakerDict_257_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) StrAnalyMaker::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__StrAnalyMakerDict_257_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   StrAnalyMaker* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new StrAnalyMaker(*(StrAnalyMaker*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef StrAnalyMaker G__TStrAnalyMaker;
static int G__StrAnalyMakerDict_257_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (StrAnalyMaker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((StrAnalyMaker*) (soff+(sizeof(StrAnalyMaker)*i)))->~G__TStrAnalyMaker();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (StrAnalyMaker*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((StrAnalyMaker*) (soff))->~G__TStrAnalyMaker();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__StrAnalyMakerDict_257_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   StrAnalyMaker* dest = (StrAnalyMaker*) G__getstructoffset();
   *dest = *(StrAnalyMaker*) libp->para[0].ref;
   const StrAnalyMaker& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* StrAnalyMaker */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncStrAnalyMakerDict {
 public:
  G__Sizep2memfuncStrAnalyMakerDict(): p(&G__Sizep2memfuncStrAnalyMakerDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncStrAnalyMakerDict::*p)();
};

size_t G__get_sizep2memfuncStrAnalyMakerDict()
{
  G__Sizep2memfuncStrAnalyMakerDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceStrAnalyMakerDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker))) {
     StrAnalyMaker *G__Lderived;
     G__Lderived=(StrAnalyMaker*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker),G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableStrAnalyMakerDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* StrAnalyMaker */
static void G__setup_memvarStrAnalyMaker(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker));
   { StrAnalyMaker *p; p=(StrAnalyMaker*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TFile),-1,-1,4,"mOverviewFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TFile),-1,-1,4,"mDatFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TFile),-1,-1,4,"mRotBgFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"pdgmass_xi=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKCentBin=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"mKPtBin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mNEventsUnweighted[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mNEventsWeighted[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mBr=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mSigRangeLeft=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mSigRangeRight=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRotNormLeftLowB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRotNormLeftHighB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRotNormRightLowB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRotNormRightHighB=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRotScale_ratio[2][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mRawSigCounts[2][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectra[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mXRawSpectraError[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectra[2][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mYRawSpectraError[2][6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"mDptSpectra[6]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarStrAnalyMakerDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncStrAnalyMaker(void) {
   /* StrAnalyMaker */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker));
   G__memfunc_setup("rotBgAnalysisInit",1750,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRotNormFactor",1759,(G__InterfaceMethod) NULL, 100, -1, G__defined_typename("Double_t"), 0, 4, 1, 4, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("StrAnalyMaker",1310,G__StrAnalyMakerDict_257_0_3, 105, G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,G__StrAnalyMakerDict_257_0_4, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - file_name u 'string' - 0 - - "
"u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotRotInvMassWithData",2251,G__StrAnalyMakerDict_257_0_5, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot "
"d - 'Double_t' 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSigCounts",1656,G__StrAnalyMakerDict_257_0_6, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - 'Int_t' 0 - centbin i - 'Int_t' 0 - ptbin "
"U 'TH1F' - 0 - hdat U 'TH1F' - 0 - hrot "
"d - 'Double_t' 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("compRawSpectra",1451,G__StrAnalyMakerDict_257_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("plotRawSpectra",1467,G__StrAnalyMakerDict_257_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Analyze",724,G__StrAnalyMakerDict_257_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__StrAnalyMakerDict_257_0_10, 85, G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&StrAnalyMaker::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__StrAnalyMakerDict_257_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StrAnalyMaker::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__StrAnalyMakerDict_257_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&StrAnalyMaker::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__StrAnalyMakerDict_257_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&StrAnalyMaker::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__StrAnalyMakerDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__StrAnalyMakerDict_257_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__StrAnalyMakerDict_257_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StrAnalyMaker::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__StrAnalyMakerDict_257_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StrAnalyMaker::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__StrAnalyMakerDict_257_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&StrAnalyMaker::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__StrAnalyMakerDict_257_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&StrAnalyMaker::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("StrAnalyMaker", 1310, G__StrAnalyMakerDict_257_0_22, (int) ('i'), G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker), -1, 0, 1, 1, 1, 0, "u 'StrAnalyMaker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~StrAnalyMaker", 1436, G__StrAnalyMakerDict_257_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__StrAnalyMakerDict_257_0_24, (int) ('u'), G__get_linked_tagnum(&G__StrAnalyMakerDictLN_StrAnalyMaker), -1, 1, 1, 1, 1, 0, "u 'StrAnalyMaker' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncStrAnalyMakerDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalStrAnalyMakerDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcStrAnalyMakerDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__StrAnalyMakerDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__StrAnalyMakerDictLN_StrAnalyMaker = { "StrAnalyMaker" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableStrAnalyMakerDict() {
  G__StrAnalyMakerDictLN_TClass.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TBuffer.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TMemberInspector.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TObject.tagnum = -1 ;
  G__StrAnalyMakerDictLN_string.tagnum = -1 ;
  G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TH1F.tagnum = -1 ;
  G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__StrAnalyMakerDictLN_TFile.tagnum = -1 ;
  G__StrAnalyMakerDictLN_StrAnalyMaker.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableStrAnalyMakerDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_string);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_TFile);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__StrAnalyMakerDictLN_StrAnalyMaker),sizeof(StrAnalyMaker),-1,29952,(char*)NULL,G__setup_memvarStrAnalyMaker,G__setup_memfuncStrAnalyMaker);
}
extern "C" void G__cpp_setupStrAnalyMakerDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupStrAnalyMakerDict()");
  G__set_cpp_environmentStrAnalyMakerDict();
  G__cpp_setup_tagtableStrAnalyMakerDict();

  G__cpp_setup_inheritanceStrAnalyMakerDict();

  G__cpp_setup_typetableStrAnalyMakerDict();

  G__cpp_setup_memvarStrAnalyMakerDict();

  G__cpp_setup_memfuncStrAnalyMakerDict();
  G__cpp_setup_globalStrAnalyMakerDict();
  G__cpp_setup_funcStrAnalyMakerDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncStrAnalyMakerDict();
  return;
}
class G__cpp_setup_initStrAnalyMakerDict {
  public:
    G__cpp_setup_initStrAnalyMakerDict() { G__add_setup_func("StrAnalyMakerDict",(G__incsetup)(&G__cpp_setupStrAnalyMakerDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initStrAnalyMakerDict() { G__remove_setup_func("StrAnalyMakerDict"); }
};
G__cpp_setup_initStrAnalyMakerDict G__cpp_setup_initializerStrAnalyMakerDict;

