/********************************************************************
* StrAnalyMakerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error StrAnalyMakerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStrAnalyMakerDict();
extern void G__cpp_setup_inheritanceStrAnalyMakerDict();
extern void G__cpp_setup_typetableStrAnalyMakerDict();
extern void G__cpp_setup_memvarStrAnalyMakerDict();
extern void G__cpp_setup_globalStrAnalyMakerDict();
extern void G__cpp_setup_memfuncStrAnalyMakerDict();
extern void G__cpp_setup_funcStrAnalyMakerDict();
extern void G__set_cpp_environmentStrAnalyMakerDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StrAnalyMaker.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__StrAnalyMakerDictLN_TClass;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TBuffer;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TMemberInspector;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TObject;
extern G__linked_taginfo G__StrAnalyMakerDictLN_string;
extern G__linked_taginfo G__StrAnalyMakerDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TH1F;
extern G__linked_taginfo G__StrAnalyMakerDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__StrAnalyMakerDictLN_TFile;
extern G__linked_taginfo G__StrAnalyMakerDictLN_StrAnalyMaker;

/* STUB derived class for protected member access */
